name: j1-binder-nbinteract
channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - ipywidgets
  - altair
  - bokeh
  - bqplot
  - matplotlib
  - networkx
  - numpy
  - scipy
  - pandas
  - seaborn
  - statsmodels
  - pip
  - pip:
    - datascience
    - vega_datasets
    - j1-nbinteract
