name: j1-binder-repository
channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - ipywidgets
  - altair
  - bokeh
  - bqplot
  - matplotlib
  - networkx
  - numpy
  - scipy
  - pandas
  - seaborn
  - statsmodels
  - pip
  - pip:
    - datascience
    - nbinteract
    - vega_datasets
