name: j1-binder-repo
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - ipywidgets
  - altair
  - matplotlib
  - bqplot
  - numpy
  - scipy
  - pandas
  - seaborn
  - statsmodels
  - matplotlib
  - pip
  - pip:
    - altair_widgets
    - nbinteract
    - datascience
